config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :users

  get 'static_pages/home'
  get 'static_pages/secret', as: 'secret' 

  get 'users/new'
  get 'users/create'
  get 'users/update'
  get 'users/destroy'

  get '/signup',  to: 'users#new'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'

  get	 '/logout',  to: 'sessions#destroy'
  delete '/logout',  to: 'sessions#destroy'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save { self.email = email.downcase }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}

  class << self
    # Returns the hash digest of the given string.
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token.
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
  	return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
  	update_attribute(:remember_digest, nil)
  	
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
    	puts "log SUCCESS"
    	log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
    	redirect_to secret_path
      # Log the user in and redirect to the user's show page.
    else
      # Create an error message.
      flash.now[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'

    end
  end

  def destroy
  	log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def secret
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to secret_path
      flash.now[:success] = 'Welcome! Ton compte est créé'

    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password,
                                 :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end

  end
  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Secret App</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "secret app", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <% if logged_in? %>
              <li><%= link_to "Log out", logout_path, method: :delete %></li>
              <li><%= link_to "Secret access", secret_path %></li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
              <li><%= link_to "Sign up", signup_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>

    </header>

    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="center">
    <h1>Bienvenue sur l'appli des secrets</h1>
    <h2>
	    <a href="static_pages/secret">Tu pourras découvrir le secret</a>
  	</h2>
    <%= link_to "Connecte-toi !", login_path, class: "btn btn-lg btn-primary" %>
    <br>
    <%= link_to "Crée un compte !", signup_path, class: "btn btn-lg btn-info" %>
</div>

app/views/static_pages/secret.html.erb
<div class="center jumbotron">
  

  <% if logged_in? %>
  <h1>42!</h1>
  <iframe width="560" height="315" src="https://www.youtube.com/embed/jwEPCn6lRo4?rel=0&amp;controls=0&amp;showinfo=0&amp;start=102&amp;autoplay=1" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

  <% else %>
  <h3>Connecte-toi pour connaître le secret !</h3>
	<%= link_to "Ok, go", login_path, class: "btn btn-lg btn-danger" %> 
  <% end %>

</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="center">
	<div class="row">
	  <div class="col-md-6 col-md-offset-3">
	  	<h1>Sign up</h1>
	    <%= form_for(@user) do |f| %>

	      <%= f.label :email %>
	      <%= f.email_field :email, class: 'form-control' %>

	      <%= f.label :password %>
	      <%= f.password_field :password, class: 'form-control' %>

	      <%= f.label :password_confirmation, "Confirmation" %>
	      <%= f.password_field :password_confirmation, class: 'form-control' %>

	      <%= f.submit "YOUPI je crée mon compte !", class: "btn btn-primary" %>
	    <% end %>
	    <br/>
	    <p>Déjà enregistré ?</p>
	    <%= link_to "Se connecter", login_path, class: "btn btn-danger" %> 
	  </div>
	</div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>